name: mega_vital
description: Mega Vital - Professional Gym & Wellness App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/body_front.png
    - assets/images/body_back.png
    - assets/images/frontal_masculino.png
    - assets/images/trasero_masculino.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
